### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by WeiFei365** [tianxuzhang/d3.v4-API-Translation#1]
@mbostock 貌似还没把 4.0 的文档更新到 WIKI 中去，都放在代码一起了；推荐个写书（API 文档）的工具：[https://www.gitbook.com/explore](https://www.gitbook.com/explore)，生成的书非常漂亮

**Comment by tianxuzhang** [comment]
是的，我感觉WIKI中的东西太多了，如果删除的话用户都会迷茫了；
而且现在mike把项目里的源码移除去真是很鸡肋啊！刚开始用的人估计要懵逼了；

**Comment by tianxuzhang** [comment]
gitbook确实很漂亮，一起啊~ :kissing_heart:
