### ISSUE TITLE
是不是d3仍然搞不定大数据呢？

### ISSUE THREAD

**Issue by Huayet** [tianxuzhang/d3.v4-API-Translation#3]
“路径这部分的API主要用来将Canvas命令转换为SVG路径的d属性的值。本质上最后还是用SVG画图。”

**Comment by tianxuzhang** [comment]
@Huayet 
我觉得：
- 数据量大的话，可以用原生的Canvas命令结合D3来画。
- 如果特别大的话，听说可以用WebGL+HTML5 Canvas 硬件3D加速渲染。
- 如果数据量大到这些办法解决不了那只能后端渲染生成图片了。
- 当然我见过最极端的是直接用集群来跑图，这个可能只在一些特殊场景下会用吧。

**Comment by Huayet** [comment]
谢谢！
